name: messenger
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-96.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^7.6.7
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  intl: ^0.19.0

  # Firebase
  firebase_core: ^2.25.2
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  image_picker: ^1.0.7
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


