// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGhvqHFRiPm316mE3Twm2pQJiwLvjtHNo',
    appId: '1:494226531974:web:b31c235eb6ae4351fd9307',
    messagingSenderId: '494226531974',
    projectId: 'messenger-4624e',
    authDomain: 'messenger-4624e.firebaseapp.com',
    storageBucket: 'messenger-4624e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk2H5UGMw-Z6gketIO9ZJ9fJaXvXZB_BE',
    appId: '1:494226531974:android:a5f2945633968d8afd9307',
    messagingSenderId: '494226531974',
    projectId: 'messenger-4624e',
    storageBucket: 'messenger-4624e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8kNKZUNyT92Xi4WjCqAfPyQ0NOntbLGo',
    appId: '1:494226531974:ios:6d18454afd5b6952fd9307',
    messagingSenderId: '494226531974',
    projectId: 'messenger-4624e',
    storageBucket: 'messenger-4624e.appspot.com',
    iosBundleId: 'com.example.messengerTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8kNKZUNyT92Xi4WjCqAfPyQ0NOntbLGo',
    appId: '1:494226531974:ios:2cd2525bb133dc51fd9307',
    messagingSenderId: '494226531974',
    projectId: 'messenger-4624e',
    storageBucket: 'messenger-4624e.appspot.com',
    iosBundleId: 'com.example.messengerTest.RunnerTests',
  );
}
